/**
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateHostForm model module.
 * @module model/CreateHostForm
 * @version 5.3.1
 */
class CreateHostForm {
    /**
     * Constructs a new <code>CreateHostForm</code>.
     * @alias module:model/CreateHostForm
     * @param id {String} Identifier of the host to be created. It will be created within the account of the host factory.
     */
    constructor(id) { 
        
        CreateHostForm.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CreateHostForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateHostForm} obj Optional instance to populate.
     * @return {module:model/CreateHostForm} The populated <code>CreateHostForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateHostForm();

            if (data.hasOwnProperty('annotations')) {
                obj['annotations'] = ApiClient.convertToType(data['annotations'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Annotations to apply to the new host
 * @member {Object} annotations
 */
CreateHostForm.prototype['annotations'] = undefined;

/**
 * Identifier of the host to be created. It will be created within the account of the host factory.
 * @member {String} id
 */
CreateHostForm.prototype['id'] = undefined;






export default CreateHostForm;

