/**
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OIDCToken model module.
 * @module model/OIDCToken
 * @version 5.3.1
 */
class OIDCToken {
    /**
     * Constructs a new <code>OIDCToken</code>.
     * OpenID Connect ID token
     * @alias module:model/OIDCToken
     */
    constructor() { 
        
        OIDCToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OIDCToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OIDCToken} obj Optional instance to populate.
     * @return {module:model/OIDCToken} The populated <code>OIDCToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OIDCToken();

            if (data.hasOwnProperty('id_token')) {
                obj['id_token'] = ApiClient.convertToType(data['id_token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id_token
 */
OIDCToken.prototype['id_token'] = undefined;






export default OIDCToken;

