/**
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PolicyVersion from './PolicyVersion';
import ResourcePermissions from './ResourcePermissions';
import ResourceSecrets from './ResourceSecrets';

/**
 * The Resource model module.
 * @module model/Resource
 * @version 5.3.1
 */
class Resource {
    /**
     * Constructs a new <code>Resource</code>.
     * @alias module:model/Resource
     */
    constructor() { 
        
        Resource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Resource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Resource} obj Optional instance to populate.
     * @return {module:model/Resource} The populated <code>Resource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Resource();

            if (data.hasOwnProperty('annotations')) {
                obj['annotations'] = ApiClient.convertToType(data['annotations'], ['String']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [ResourcePermissions]);
            }
            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], 'String');
            }
            if (data.hasOwnProperty('policy_versions')) {
                obj['policy_versions'] = ApiClient.convertToType(data['policy_versions'], [PolicyVersion]);
            }
            if (data.hasOwnProperty('restricted_to')) {
                obj['restricted_to'] = ApiClient.convertToType(data['restricted_to'], ['String']);
            }
            if (data.hasOwnProperty('secrets')) {
                obj['secrets'] = ApiClient.convertToType(data['secrets'], [ResourceSecrets]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} annotations
 */
Resource.prototype['annotations'] = undefined;

/**
 * @member {String} created_at
 */
Resource.prototype['created_at'] = undefined;

/**
 * @member {String} id
 */
Resource.prototype['id'] = undefined;

/**
 * @member {String} owner
 */
Resource.prototype['owner'] = undefined;

/**
 * @member {Array.<module:model/ResourcePermissions>} permissions
 */
Resource.prototype['permissions'] = undefined;

/**
 * @member {String} policy
 */
Resource.prototype['policy'] = undefined;

/**
 * @member {Array.<module:model/PolicyVersion>} policy_versions
 */
Resource.prototype['policy_versions'] = undefined;

/**
 * @member {Array.<String>} restricted_to
 */
Resource.prototype['restricted_to'] = undefined;

/**
 * @member {Array.<module:model/ResourceSecrets>} secrets
 */
Resource.prototype['secrets'] = undefined;






export default Resource;

