/**
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResourcePermissions model module.
 * @module model/ResourcePermissions
 * @version 5.3.1
 */
class ResourcePermissions {
    /**
     * Constructs a new <code>ResourcePermissions</code>.
     * @alias module:model/ResourcePermissions
     */
    constructor() { 
        
        ResourcePermissions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResourcePermissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourcePermissions} obj Optional instance to populate.
     * @return {module:model/ResourcePermissions} The populated <code>ResourcePermissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourcePermissions();

            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], 'String');
            }
            if (data.hasOwnProperty('privilege')) {
                obj['privilege'] = ApiClient.convertToType(data['privilege'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} policy
 */
ResourcePermissions.prototype['policy'] = undefined;

/**
 * @member {String} privilege
 */
ResourcePermissions.prototype['privilege'] = undefined;

/**
 * @member {String} role
 */
ResourcePermissions.prototype['role'] = undefined;






export default ResourcePermissions;

