/**
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WhoAmI model module.
 * @module model/WhoAmI
 * @version 5.3.1
 */
class WhoAmI {
    /**
     * Constructs a new <code>WhoAmI</code>.
     * Information about the client making a request
     * @alias module:model/WhoAmI
     */
    constructor() { 
        
        WhoAmI.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WhoAmI</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WhoAmI} obj Optional instance to populate.
     * @return {module:model/WhoAmI} The populated <code>WhoAmI</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WhoAmI();

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('client_ip')) {
                obj['client_ip'] = ApiClient.convertToType(data['client_ip'], 'String');
            }
            if (data.hasOwnProperty('token_issued_at')) {
                obj['token_issued_at'] = ApiClient.convertToType(data['token_issued_at'], 'String');
            }
            if (data.hasOwnProperty('user_agent')) {
                obj['user_agent'] = ApiClient.convertToType(data['user_agent'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The account attribute of the client provided access token.
 * @member {String} account
 */
WhoAmI.prototype['account'] = undefined;

/**
 * The request client IP address as determined by Conjur. This same IP address appears in application logs and audit logs.
 * @member {String} client_ip
 */
WhoAmI.prototype['client_ip'] = undefined;

/**
 * The issued timestamp, that is, when the provided access token was created (iat field in the JWT)
 * @member {String} token_issued_at
 */
WhoAmI.prototype['token_issued_at'] = undefined;

/**
 * The incoming request HTTP user agent header.
 * @member {String} user_agent
 */
WhoAmI.prototype['user_agent'] = undefined;

/**
 * The username attribute of the provided access token.
 * @member {String} username
 */
WhoAmI.prototype['username'] = undefined;






export default WhoAmI;

